apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: tct-dev
  name: fluentd-elasticsearch
  labels:
    k8s-app: fluentd-logging
spec:
  selector:
    matchLabels:
      name: fluentd-elasticsearch
  template:
    metadata:
      labels:
        name: fluentd-elasticsearch
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: fluentd-elasticsearch
        image: gydtc/fluentd-elasticsearch:1.20
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers 
          mountPath: /var/lib/docker/containers
          readOnly: true 
      terminationGracePeriodSeconds: 30
      volumes: 
      - name: varlog 
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:          
          path: /var/lib/docker/containers