kind: Deployment
apiVersion: apps/v1 
metadata:
  name: nfs-client-provisioner
  namespace: kube-system
spec:
  selector:     
    matchLabels:       
      app: nfs-client-provisioner
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nfs-client-provisioner
    spec:
      serviceAccountName: nfs-client-provisioner
      containers:
        - name: nfs-client-provisioner
          image: quay.io/external_storage/nfs-client-provisioner:latest
          volumeMounts:
            - name: nfs-client-root
              mountPath: /persistentvolumes
          env:
            - name: PROVISIONER_NAME
              value: fuseim.pri/ifs
            - name: NFS_SERVER
              value: 10.129.76.132
            - name: NFS_PATH
              value: /data/nfs-pv
      volumes:
        - name: nfs-client-root
          nfs:
            server: 10.129.76.132
            path: /data/nfs-pv