---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pvs-6
spec:
  capacity:
    storage: 200M
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.129.76.132
    path: "/usr/local/kubernetes/redis/pv6"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pvs-7
spec:
  capacity:
    storage: 200M
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.129.76.132 
    path: "/usr/local/kubernetes/redis/pv7"