apiVersion: v1 
kind: Pod 
metadata:  
  name: test-downwardapi-volume  
  labels:
    zone: us-est-coast
    cluster: test-cluster1
    rack: rack-22 
spec:  
  containers:  
  - name: client-container  
    image: busybox  
    command: ["sh", "-c"]  
    args:
    - while true; do           
        if [[ -e /podInfo/labels ]]; then
          echo -en '\n\n'; cat /podInfo/labels; 
        fi;
        sleep 5;         
      done;  
    volumeMounts:  
    - name: podInfo  
      mountPath: /podInfo  
      readOnly: false  
  
  volumes:  
  - name: podInfo  
    projected:  
      sources:  
      - downwardAPI:  
          items:
            - path: "labels"  
              fieldRef: 
                fieldPath: metadata.labels 

#https://kubernetes.io/zh/docs/concepts/storage/volumes/#projected