apiVersion: v1 
kind: ConfigMap 
metadata:   
  name: mysql   
  labels:     
    app: mysql 
data:   
  master.cnf: |     
    # 主节点 MySQL 的配置文件     
    [mysqld]     
    log-bin   
  slave.cnf: |     
    # 从节点 MySQL 的配置文件     
    [mysqld]     
    super-read-only 
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: cmp
  annotations:
    kubesphere.io/creator: lzn
data:
  password: cm9vdFB3ZEBAITUzNA==
type: Opaque